name: CI/CD
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        
      - name: Install packages
        run: pnpm install
        
      - name: Install Turborepo
        run: pnpm add turbo --global
        
      - name: Build
        run: turbo build

      - name: Build
        run: turbo deploy
